// myPromise - ახალი Promise ობიექტია, რომელიც ასინქრონული ოპერაციის წარმატებას ან შეცდომას აღწერს
const myPromise = new Promise((fulfill, fail) => {
    // success ფაქტორი: თუ trueა — ოპერაცია წარმატებულია, თუ false — შეცდომაა
    let success = true;

    // პირობაზე დაყრდნობით ვწყვეტთ, შევასრულოთ თუ არა (fulfill) ან ჩავაგდოთ (fail) პრომისი
    if (success) {
        // fulfill გამოძახება ნიშნავს, რომ პრომისი 'გადაწყვეტილია' წარმატებით
        fulfill("ოპერაცია წარმატებით შესრულდა!");
    } else {
        // fail გამოძახება ნიშნავს, რომ პრომისი 'ჩავარდა' შეცდომით
        fail("რაღაც შეცდომა მოხდა!");
    }
});

// then/catch/finally ჯაჭვი — აჩვენებს, რა უნდა მოხდეს წარმატების, შეცდომის და დასრულების დროს
myPromise
    .then(result => {
        // then იღებს წარმატებით მიღებულ მნიშვნელობას (result) და ბეჭდავს კონსოლში
        console.log(result);
    })
    .catch(error => {
        // catch იჭერს შეცდომას (თუ პრომისი ჩაიგდო) და ბეჭდავს კონსოლში
        console.log(error);
    })
    .finally(() => {
        // finally ყოველთვის შესრულდება — მიუხედავად იმისა, იყო წარმატება თუ შეცდომა
        console.log("Promise დასრულდა");
    });
